version: "3.8"

services:
  flowcrm:
    build: .
    container_name: flowcrm
    restart: unless-stopped
    networks:
      - Vizionsnet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flowcrm.rule=Host(`app.vizions.com.br`)"
      - "traefik.http.routers.flowcrm.entrypoints=websecure"
      - "traefik.http.routers.flowcrm.tls.certresolver=letsencrypt"
      - "traefik.http.services.flowcrm.loadbalancer.server.port=80"

networks:
  Vizionsnet:
    external: true
    name: Vizionsnet